config/routes.rb
Moochify::Application.routes.draw do

  get "reviews/create"
  root 'home#show', as: :home

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users, :except => [:index]
  resources :equipment
  resources :orders, :only => [:index, :show, :create]
  resources :reviews

  resources :sessions
  resources :results, :except => [:create] 

  post 'results', to: 'results#index'

  scope 'api', defaults: {format: :json} do
    resources :equipment, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:index, :create, :update, :destroy]
  end

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base


  validates_presence_of :name
  validates_presence_of :current_daily_cost
  validates_numericality_of :current_daily_cost
  validates_presence_of :description
  validates_presence_of :availability
  
  belongs_to :user
  has_many :orders

  # The code below is for displaying the avatar photos
  # for both users and pieces of equipment

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController

  before_filter :equipment_edits, only: [:edit, :update]

  def new
    @equipment = Equipment.new
  end

  def create

    # MISSING USER_ID WHEN USING API ENDPOINT -> 
    equipment = current_user.equipment.new(equipment_params)

    respond_to do |format|
      if equipment.save
        format.html { redirect_to equipment_index_path, notice: 'Equipment was successfully created.' }
        format.json { render json: equipment, status: :created }
      else
        format.html {render :new }
        format.json { render json: equipment.errors, status: :unprocessable_entity }
      end
    end

  end

  def edit
    @equipment = Equipment.find(params[:id])
  end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
  def update
    equipment = Equipment.find(params[:id])
    respond_to do |format|
      if equipment.update_attributes(equipment_params)
        format.html { redirect_to equipment, notice: 'Equipment was successfully updated.' }
        format.json { render json: equipment, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @equipment = Equipment.where(user_id: current_user)
    
    respond_to do |format|
      format.html {  }
      format.json { render json: @equipment, status: :ok }
    end

  end


  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    equipment = Equipment.find(params[:id])
    equipment.destroy
    respond_to do |format|
      format.html { redirect_to equipment_index_path, notice: 'Equipment was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  def show
    @equipment = Equipment.find(params[:id])
    @reviews = Review.find_by_sql([
      'SELECT reviews.title, reviews.comment ' +
      'FROM reviews ' +
      'INNER JOIN orders ' +
      'ON reviews.order_id = orders.id ' +
      'INNER JOIN equipment ' +
      'ON orders.equipment_id = equipment.id ' +
      'WHERE equipment.id = ?',
      "#{params[:id]}"
      ])
    @myLat = User.find(@equipment.user_id).latitude
    @myLng = User.find(@equipment.user_id).longitude
    @owner = User.find(@equipment.user_id)
  end

private

  def equipment_params
    params.require(:equipment).permit(:name, :current_daily_cost, :description, :availability, :avatar)
  end

  # The method below prevents a user from editing another user's equipment

  def equipment_edits
    redirect_to home_path if current_user.id != Equipment.find(params[:id]).user_id
  end

end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/views/equipment/edit.html.erb
<div class="container equip-background">
  <div class="left-side">
  <%= image_tag @equipment.avatar.url(:medium), class: "equip-image" %>
  </div>
  <div class="right-side">
    <h1>Edit Equipment</h1>

    <%= form_for @equipment, :html => { :multipart => true } do |f| %>

      <%= f.label :name %><br>
      <%= f.text_field :name %><br>

      <%= f.label :current_daily_cost %><br>
      <%= f.number_field :current_daily_cost %><br>

      <%= f.label :description %><br>
      <%= f.text_area :description %><br>

      <%= f.label :availability %><br>
      <%= f.text_field :availability %><br>

      <%= f.file_field :avatar %>

      <%= f.submit "Save", class: "btn btn-success btn-lg" %>
      <%= link_to "Back to Inventory", equipment_index_path %>

    <% end %>
  </div>
</div>

app/views/equipment/index.html.erb
<div class="container">
  <h1>Inventory</h1>

  <% @equipment.each do |e| %>
	<div class="equip-listing">
      <%= image_tag e.avatar.url(:thumb), :class => "equip-thumb" %>
	    <h2><%= e.name %></h2>
	    <h3><%= e.availability %> <%= number_to_currency(e.current_daily_cost) %></h3>
	    <p><%= e.description %></p>
	    <%= button_to "Edit", edit_equipment_path(e.id), :method => :get, class: "btn" %>
	    <%= button_to "Remove", equipment_path(e.id), :method => :delete, class: "btn btn-danger" %>
	    <%= link_to "View", equipment_path(e.id), class: "btn btn-success" %>	    
    </div>
  <% end %>

app/views/equipment/new.html.erb
<div class="container equip-background">
	<div class="left-side">
        <%= image_tag @equipment.avatar.url(:medium) %>
	</div>
  <div class="right-side">
		<h1>Add equipment</h1>

		<%= form_for @equipment, :html => { :multipart => true } do |f| %>
		  
		  <%= f.text_field :name, placeholder: "Name" %><br>
		  <%= f.text_area :description, placeholder: "Description" %><br>
		  <%= f.number_field :current_daily_cost, value: 5.00, min: 5.00, step: 0.25 %><br>
		  <%= f.text_field :availability, placeholder: "Availability" %><br>
      <%= f.file_field :avatar %>
		  <%= f.submit "Add Equipment", class: "btn btn-success btn-lg" %>
		  <%= link_to "Cancel", equipment_index_path %>

		<%end%>
	</div>
</div>

app/views/equipment/show.html.erb
<div class="container">

<!-- Equipment Specs Row -->

	<div class="row profile-review">
		<div class="col-md-4">
			<%= image_tag @equipment.avatar.url(:medium) %>
		</div>

		<div class="col-md-8">
			<div class="equip-specs">
				<h2><%= @equipment.name %></h2>
				<h1><%= number_to_currency(@equipment.current_daily_cost) %></h1>
				<p><strong>Description</strong>: <%= @equipment.description %></p><br>
				<p><strong>Availability:</strong> <%= @equipment.availability %></p>

				<h1>Reserve this item.</h1>
				<%= form_tag orders_path do %>

          <%= date_field_tag :start_date, Date.today  %>
          <%= date_field_tag :end_date, Date.today+7  %>

				  <%= hidden_field_tag :equipment_id, @equipment.id %>
				  <%= hidden_field_tag :daily_cost, @equipment.current_daily_cost %>

				  <%= submit_tag "Place order", class: "btn btn-success btn-lg"%>
				  <% end %>
		 	</div>	
		</div>
	</div> <!-- End Equipment Specs Row -->

	<!-- Reviews Row -->

	<div class="row profile-review"> 
		<div class="col-md-5">
			<h1>Owner</h1>
			<%= image_tag @owner.avatar.url(:thumb) %>
			<h2><%= @owner.first_name %> <%= @owner.last_name %></h2>
			<p><%= @owner.bio %></p>
		</div>
		<div class="col-md-2">
		</div>
		<div class="col-md-5">
			<h1>Reviews</h1>
			<% @reviews.each do |r| %>
			    <div class="individual-reviews">
					<p><strong><%= r.title %></strong></p>
					<p>"<%= r.comment %>"</p>
			    </div>
			<% end %>
		</div>	
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="content-wrapper">
			    <div id="profile-map-canvas">
	            </div>
            </div>
        </div>
    </div> <!-- End Container -->
</div>

<script>

	var map;
	var myLat = <%= raw @myLat.to_json %>;
	var myLng = <%= raw @myLng.to_json %>;

	map = new google.maps.Map(document.getElementById('profile-map-canvas'), {
	  zoom: 13,
	  center: new google.maps.LatLng(myLat, myLng)
	});

	var myLatlng = new google.maps.LatLng(myLat, myLng);
	var marker = new google.maps.Marker({
	  position: myLatlng,
	  map: map
	});

</script>