config/routes.rb
Moochify::Application.routes.draw do

  get "reviews/create"
  root 'home#show', as: :home

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users, :except => [:index]
  resources :equipment
  resources :orders, :only => [:index, :show, :create]
  resources :reviews

  resources :sessions
  resources :results, :except => [:create] 

  post 'results', to: 'results#index'

  scope 'api', defaults: {format: :json} do
    resources :equipment, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:index, :create, :update, :destroy]
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :equipment
  has_many :reviews
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  before_filter :orders_show, only: [:show]

  def index
    @orders = Order.where(user_id: current_user)
  end

  def show
    @order = Order.find(params[:id])
    @user = User.find(@order.user_id)
    @equipment = Equipment.find(@order.equipment_id)
    @reviews = Review.where(order_id: params[:id])
  end

  def create

    default_start = Date.today.to_s
    default_end = (Date.today + 7).to_s

    my_daily_cost = params[:daily_cost]
    my_equipment_id = params[:equipment_id]

    if params[:start_date].blank?
      order = current_user.orders.new(daily_cost: my_daily_cost, equipment_id: my_equipment_id, start_date: default_start, end_date: default_end)
    else
      order = current_user.orders.new(params.permit(:start_date, :end_date, :daily_cost, :equipment_id))
    end

    order.save
    redirect_to order_path(order)  

  end

private
  
  # The method below prevents a user from viewing another user's order

  def orders_show
    redirect_to home_path if current_user.id != Order.find(params[:id]).user_id
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<div class="container">

	<h2>Order History</h2>
	
	<div class="row orders-header">
    <div class="col-md-4 col-sm-4"><h1>Equipment</h1></div>
    <div class="col-md-4 col-sm-4"><h1>Order Details</h1></div>
    <div class="col-md-4 col-sm-4"><h1>Owner</h1></div>
	</div>

	<% @orders.each do |o| %>
	<div class="row">
    <div class="order-hist">
  		<div class="col-md-4 col-sm-4">
    		<% equipment = Equipment.find(o.equipment_id) %>
        <strong><p><%= link_to "#{equipment.name}", equipment_path(equipment) %></p></strong>
        <%= image_tag equipment.avatar.url(:thumb) %>
  	  </div>
      <div class="col-md-4 col-sm-4">
  	    <p><strong>Start date:</strong> <%= o.start_date %></p>
  	    <p><strong>End date:</strong> <%= o.end_date %></p>
  	    <p><strong>Daily rate:</strong> <%= number_to_currency(o.daily_cost) %></p>
  	    <% dayCount = (o.end_date - o.start_date).to_i %>
  	    <p><strong>Number of days:</strong> <%= dayCount %></p>
  	    <p><strong>Total cost:</strong> <%= o.daily_cost * dayCount %></p>
        <%= link_to "View Order", order_path(o) %>
  	  </div>
      <div class="col-md-4 col-sm-4">
    		<% owner = User.find(equipment.user_id) %>
  	    <strong><p><%= owner.first_name.titleize %> <%= owner.last_name.titleize %></p></strong>
        <%= image_tag owner.avatar.url(:thumb) %>
      </div>
    </div>
  </div> <!-- End Row -->
  <% end %>

</div> <!-- End Container -->

<!-- <h1>Reviews</h1> -->

app/views/orders/show.html.erb
<div class="container">
	<div class="show-order">
		<div class="row order-show-row">
			<div class="col-md-4">		
				<%= image_tag @equipment.avatar.url(:medium) %>
			</div>

		<div class="col-md-8">
			<div class="order-confirm">
				<h2>Your order has been processed.</h2>
				<h1><%= @equipment.name %></h1>
				<h1>Order Details:</h1>
				<p>Cost per day: <%= number_to_currency(@order.daily_cost) %></br>
					<% dayCount = (@order.end_date - @order.start_date).to_i %>
					Number of days: <%= dayCount %></br></br>
					Your total: <strong><%= number_to_currency(@order.daily_cost * dayCount) %></strong></p>
				  <%= link_to "Order History", orders_path, class: "btn btn-success btn-lg"%>
			</div>

				<% @reviews.each do |r| %>
					<p><%= r.title %></p>
					<p><%= r.comment %></p>
				<% end %>

	      <%= form_tag reviews_path do %>
	    <div class="form-group">
	        <%= text_field_tag :title, nil, placeholder: "Enter a title...", class: "form-control" %></br>
        </div>

	       <div class="form-group">
	        <%= text_area_tag :comment, nil, placeholder: "Review goes here...", class: "form-control"  %></br>
				  <%= hidden_field_tag :order_id, @order.id %>
	        <%= submit_tag  "Post", class: "btn btn-success btn-lg home-submit" %>
	      <% end %>
			</div>
				
		</div>
	</div>
</div>